App50Amigos/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from .funcionalidades import  *
from django.conf import settings

app_name = 'App50Amigos'

urlpatterns = [
   path('', views.index, name='index'),
   path('administrador/', views.panelAdmin, name='panel_admin'),
   path('usuario/<int:id_tableta>/<int:num_mesa>/<str:ubicacion>/<int:id_order>/',
        views.panelUser, name='panel_user'),
   path('carrito/', views.carrito, name='carrito'),
   path('votación', views.votacion, name='votacion'),
   path('registro/', views.registro, name = 'registro'),
   path('bienvenida/<int:id_tableta>/<int:num_mesa>/<str:ubicacion>/', views.fondo, name='bienvenida')
   #path('asignacion_mesa/<parametros>')
]

Proyecto50Amigos/urls.py
from django.contrib import admin
from django.urls import path, include
from App50Amigos import views
from django.conf import settings 
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include

urlpatterns = [
   path('admin/', admin.site.urls),
   path('', include('App50Amigos.urls')),
   path('accounts/', include('django.contrib.auth.urls'))
]
urlpatterns += staticfiles_urlpatterns()

App50Amigos/models.py
from django.db import models

class Administrador(models.Model):
    id_Administrador = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=200)
    apellidoP = models.CharField(max_length=200)
    apellidoM = models.CharField(max_length=200)
    edad = models.IntegerField(default=0)
    contrasenia = models.CharField(max_length=500)

class Encargado_Tableta(models.Model):
    id_Encargado = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=200)
    apellidoP = models.CharField(max_length=200)
    apellidoM = models.CharField(max_length=200)
    edad = models.IntegerField(default=0)
    contrasenia = models.CharField(max_length=500)

class Menu(models.Model):
    id_Menu = models.AutoField(primary_key=True)
    id_Admin = models.ForeignKey(Administrador, on_delete=models.SET_NULL, null=True)

class Platillo(models.Model):
    CATEGORIA = (
        ('entrada', 'Entrada'),
        ('plato_fuerte', 'Plato Fuerte'),
        ('postre', 'Postre'),
        ('bebida', 'Bebida'),
        ('helado', 'Helado'),
    )
    id_Platillo = models.AutoField(primary_key=True)
    id_Administrador = models.ForeignKey(Administrador, on_delete=models.SET_NULL, null=True)
    id_Menu = models.ForeignKey(Menu, on_delete=models.SET_NULL, null=True)
    categoria = models.CharField(max_length=20, choices=CATEGORIA)
    nombre = models.CharField(default = 0, max_length= 20)
    costo = models.IntegerField(default=0)
    descripcion = models.TextField()
    imagen = models.CharField(max_length=1000)

class Tableta(models.Model):
    id_Tableta = models.IntegerField(primary_key=True)
    id_Encargado = models.ForeignKey(Encargado_Tableta, on_delete=models.SET_NULL, null=True)

class Orden(models.Model):
    id_Orden = models.IntegerField(primary_key=True)
    id_Tableta = models.ForeignKey(Tableta, on_delete=models.SET_NULL, null=True)

class Ordenar(models.Model):
    id_Orden = models.ForeignKey(Orden, on_delete=models.SET_NULL, null=True)
    platillos = models.ManyToManyField(Platillo, through='PlatilloEnOrden')
class PlatilloEnOrden(models.Model):
    orden = models.ForeignKey(Ordenar, on_delete=models.CASCADE)
    platillo = models.ForeignKey(Platillo, on_delete=models.CASCADE)
    cantidad = models.PositiveIntegerField()

class Mesa(models.Model):
    UBICACIONES = (
        ('terraza', 'Terraza'),
        ('jardin', 'Jardin'),
        ('comedor', 'Comedor'),
        ('balcon', 'Balcon'),
    )
    id_Mesa = models.AutoField(primary_key=True)
    ubicacion = models.CharField(max_length=20, choices=UBICACIONES)

class Estar(models.Model):
    id_Mesa = models.ForeignKey(Mesa, on_delete=models.SET_NULL, null=True)
    id_Tableta = models.ForeignKey(Tableta, on_delete=models.SET_NULL, null=True)
    fecha = models.DateField()
    ubicacion = models.CharField(max_length=20, blank=True)

    def save(self, *args, **kwargs):
        if self.id_Mesa:
            self.ubicacion = self.id_Mesa.ubicacion
        super().save(*args, **kwargs)

App50Amigos/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth.models import Group
from django.contrib.auth.forms import ReadOnlyPasswordHashField

from .models import Account


class RegistrationForm(forms.ModelForm):
    password = forms.CharField(label='ubicacion', widget=forms.PasswordInput)
    class Meta:
        model = Account
        fields = ('mesa', 'ubicacion')

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user


class UserCreationForm(forms.ModelForm):
    password1 = forms.CharField(label='ubicación')
    password2 = forms.CharField(label='confirma ubicación')

    class Meta:
        model = Account
        fields = ('mesa', 'ubicacion')

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserChangeForm(forms.ModelForm):
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = Account
        fields = ('mesa', 'ubicacion')

    def clean_password(self):
        # Regardless of what the user provides, return the initial value.
        # This is done here, rather than on the field, because the
        # field does not have access to the initial value
        return self.initial["password"]
    
class AgregarNombre(forms.Form):
    nombre = forms.CharField(label='Ingresa tu nombre', max_length=10)

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', "first_name", "last_name", "email", "password1","password2"]

App50Amigos/views.py
from django.shortcuts import render, HttpResponse, redirect
from urllib.parse import urlencode
from .models import *
from .forms import *
from django.http import JsonResponse
from django.urls import reverse

from django.contrib import messages
from .forms import CustomUserCreationForm
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from .models import *
from .funcionalidades import *
import uuid
# Create your views here.


def index(request):

    if request.method == 'POST':
        num_mesa = request.POST.get('NumMesa')
        ubicacion = request.POST.get('ubicacion')
        id_encargado = request.POST.get('id_Encargado')
        id_tableta = request.POST.get('id_tableta')

        return redirect('App50Amigos:bienvenida', id_tableta, num_mesa, ubicacion)

    return render(request,'index.html')


def fondo(request, id_tableta, num_mesa, ubicacion):

    if request.method == 'POST':
        id_order = int(uuid.uuid4().int)
        print(id_order)
        return redirect('App50Amigos:panel_user', id_tableta, num_mesa, ubicacion, id_order)

    return render(request, 'fondo.html')

def panelAdmin(request):
    entradas = Platillo.objects.filter(categoria='Entrada')
    platos_fuerte = Platillo.objects.filter(categoria='Plato Fuerte')
    bebidas = Platillo.objects.filter(categoria='Bebida')
    postres = Platillo.objects.filter(categoria='Postre')
    helados = Platillo.objects.filter(categoria='Helado')
    return render(request, 'panels/panel_admin.html', {'entradas': entradas,
                                                       'platos_fuertes': platos_fuerte,
                                                       'bebidas': bebidas,
                                                       'postres': postres,
                                                       'helados': helados})

def panelUser(request, id_tableta, num_mesa, ubicacion, id_order):
    entradas = Platillo.objects.filter(categoria='Entrada')
    platos_fuerte= Platillo.objects.filter(categoria='Plato Fuerte')
    bebidas = Platillo.objects.filter(categoria='Bebida')
    postres = Platillo.objects.filter(categoria='Postre')
    return render(request, 'panels/panel_user.html',  {'entradas': entradas,
                                                       'platos_fuertes': platos_fuerte,
                                                       'bebidas': bebidas,
                                                       'postres': postres,
                                                       'num_mesa': num_mesa,
                                                       'ubicacion': ubicacion})

def carrito(request):
    return render(request, 'panels/pedido.html')

def votacion(request):
    return render(request, 'panels/votacion.html')

def registro(request):
    data = {
        'form': CustomUserCreationForm()
    }
    if request.method == "POST":
        formulario = CustomUserCreationForm(data=request.POST)
        if formulario.is_valid():
            usuario = formulario.save()
            usuario.save()
            user = authenticate(username = formulario.cleaned_data["username"], password = formulario.cleaned_data["password1"])
            login(request,user)
            messages.success(request, "Registro exitoso, inicia sesión")
            return redirect(to="App50Amigos:P1")
        data["form"] = formulario

    return render(request, 'registration/registration.html', data)

App50Amigos/templates/panels/panel_admin.html
{%load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>50 Amigos - Bienvenido</title>
    <link href='https://fonts.googleapis.com/css?family=Nunito' rel='stylesheet'>
    <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico '%}" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'css/panel_admin.css'%}" rel="stylesheet" />
    <script src="https://kit.fontawesome.com/d5b36fd0cc.js" crossorigin="anonymous"></script>
</head>

<body>
    <header>
        <div class="logo">
            <p>Administrador Nombre</p>
            <img class="logo_img" src="{% static 'assets/logos/50amigos.png'%}" alt="">
        </div>
        <div class="panel_center">
            <div class="top_table">
                <form class="buscador" action="">
                    <input class="search_text" type="text" placeholder="Buscar platillo">
                    <button>
                        <img class="search_button" src="{% static 'assets/icon/search.png'%}">
                    </button>
                </form>
                <button class="button_panel">
                    <a class="iniciar" href="{% url 'logout'%}"> <p>Cerrar sesión</p></a>  
                </button>
            </div>
            <div class="message_admin">
                <p class="admin_title">Bienvenido de nuevo, Nombre</p>
                <p class="question">Elige una categoria para empezar</p>
            </div>
        </div>
    </header>
    <section class="content">
        <div class="category_card">
            <p>Entradas</p>
            <img src="{% static 'assets/categories/entrada.jpg'%}" alt="">
        </div>
        <div class="category_card">
            <p>Platos <br> principales</p>
            <img src="{% static 'assets/categories/plato_fuerte.jpg' %}" alt="">
        </div>
        <div class="category_card">
            <p>Bebidas</p>
            <img src="{% static 'assets/categories/bebidas.jpg' %}" alt="">
        </div>
        <div class="category_card">
            <p>Postres</p>
            <img src="{% static 'assets/categories/postre.jpg' %}" alt="">
        </div>
        <div class="category_card">
            <p>Helados</p>
            <img src="{% static 'assets/categories/helado.jpg' %}" alt="">
        </div>
    </section>
    <section class="entradas">
        {% for entrada in entradas%}
            <div class="card">
                <img src="{{entrada.imagen}}" alt="">
                <div class="info">
                    <p class="nombre_platillo">{{entrada.nombre}}</p>
                    <p class="descripcion_platillo">{{entrada.descripcion}} </p>
                    <div class="add_bill">
                        <p class="costo_platillo">MX${{entrada.costo}}</p>
                        <a href="">+</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </section>
    <section class="postres">
        {% for postre in postres%}
            <div class="card">
                <img src="{{postre.imagen}}" alt="">
                <div class="info">
                    <p class="nombre_platillo">{{postre.nombre}}</p>
                    <p class="descripcion_platillo">{{postre.descripcion}} </p>
                    <div class="add_bill">
                        <p class="costo_platillo">MX${{postre.costo}}</p>
                        <a href="">+</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </section>
    <section class="platos_fuertes">
        {% for plato_fuerte in platos_fuertes%}
            <div class="card">
                <img src="{{plato_fuerte.imagen}}" alt="">
                <div class="info">
                    <p class="nombre_platillo">{{plato_fuerte.nombre}}</p>
                    <p class="descripcion_platillo">{{plato_fuerte.descripcion}} </p>
                    <div class="add_bill">
                        <p class="costo_platillo">MX${{plato_fuerte.costo}}</p>
                        <a href="">+</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </section>
    <section class="bebidas">
        {% for bebida in bedidas%}
            <div class="card">
                <img src="{{bebida.imagen}}" alt="">
                <div class="info">
                    <p class="nombre_platillo">{{bebida.nombre}}</p>
                    <p class="descripcion_platillo">{{bebida.descripcion}} </p>
                    <div class="add_bill">
                        <p class="costo_platillo">MX${{bebida.costo}}</p>
                        <a href="">+</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </section>
    <section class="helados">
        {% for helado in helados%}
            <div class="card">
                <img src="{{helado.imagen}}" alt="">
                <div class="info">
                    <p class="nombre_platillo">{{helado.nombre}}</p>
                    <p class="descripcion_platillo">{{helado.descripcion}} </p>
                    <div class="add_bill">
                        <p class="costo_platillo">MX${{helado.costo}}</p>
                        <a href="">+</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </section>
</body>
<script src="https://code.jquery.com/jquery-3.7.0.js"></script>
<script src="{% static 'js/index.js'%}"></script>

</html>

App50Amigos/templates/panels/panel_user.html
{%load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>50 Amigos - Bienvenido</title>
    <link href='https://fonts.googleapis.com/css?family=Nunito' rel='stylesheet'>
    <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico '%}" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'css/panel_user.css'%}" rel="stylesheet" />
    <script src="https://kit.fontawesome.com/d5b36fd0cc.js" crossorigin="anonymous"></script>
</head>

<body class="body_initial">
    <header>
        <div class="logo">
            <p>Mesa {{num_mesa}}, {{ubicacion}}</p>
            <img class="logo_img" src="{% static 'assets/logos/50amigos.png'%}" alt="">
        </div>
        <div class="panel_center">
            <p class="menu_title">Menú principal</p>
            <p class="question">¿Qué deseas comer hoy?</p>
        </div>
        <div class="buttons">
            <button class="button_panel">
                <a href="{% url 'App50Amigos:carrito'%}">
                    <p>Carrito</p>
                    <img src="{% static 'assets/icon/shop.png'%}" alt="">
                </a>
            </button>

            <button class="button_panel">
                <a href="{% url 'App50Amigos:votacion'%}">
                    <p>Helado</p>
                    <img src="{% static 'assets/icon/ice_cream.png'%}" alt="">
                </a>
            </button>

        </div>
        <div class="buttons_menu">
            <button class="button_panel_menu">
                <a href="{% url 'App50Amigos:carrito'%}">
                    <p>Carrito</p>
                    <img src="{% static 'assets/icon/shop.png'%}" alt="">
                </a>
            </button>

            <button class="button_panel_menu">
                <a href="{% url 'App50Amigos:votacion'%}">
                    <p>Helado</p>
                    <img src="{% static 'assets/icon/ice_cream.png'%}" alt="">
                </a>
            </button>

            <button class="button_panel_menu button_menu" id="return_menu">
                <p>Menú</p>
                <img src="{% static 'assets/icon/menu.png'%}" alt="">

            </button>
        </div>

    </header>
    <div class="aux"></div>
    <section class="content">
        <button id="category_entrada">
            <p>Entradas</p>
            <img src="{% static 'assets/categories/entrada.jpg'%}" alt="">
        </button>
        <button id="category_plato">
            <p>Platos <br> principales</p>
            <img src="{% static 'assets/categories/plato_fuerte.jpg' %}" alt="">
        </button>
        <button id="category_bebida">
            <p>Bebidas</p>
            <img src="{% static 'assets/categories/bebidas.jpg' %}" alt="">
        </button>
        <button id="category_postre">
            <p>Postres</p>
            <img src="{% static 'assets/categories/postre.jpg' %}" alt="">
        </button>
    </section>
    <section class="entradas" id="entradas">
        {% for entrada in entradas%}
        <div class="card">
                <img src="{{entrada.imagen}}" alt="">
                <div class="info">
                    <p class="nombre_platillo">{{entrada.nombre}}</p>
                    <p class="descripcion_platillo">{{entrada.descripcion}} </p>
                    <div class="add_bill">
                        <p class="costo_platillo">MX${{entrada.costo}}</p>
                        <a href="">+</a>
                    </div>
                </div>
        </div>
        {% endfor %}
    </section>
    <section class="postres">
        {% for postre in postres%}
        <div class="card">
            <img src="{{postre.imagen}}" alt="">
            <div class="info">
                <p class="nombre_platillo">{{postre.nombre}}</p>
                <p class="descripcion_platillo">{{postre.descripcion}} </p>
                <div class="add_bill">
                    <p class="costo_platillo">MX${{postre.costo}}</p>
                    <a href="">+</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </section>
    <section class="platos_fuertes">
        {% for plato_fuerte in platos_fuertes%}
        <div class="card">
            <img src="{{plato_fuerte.imagen}}" alt="">
            <div class="info">
                <p class="nombre_platillo">{{plato_fuerte.nombre}}</p>
                <p class="descripcion_platillo">{{plato_fuerte.descripcion}} </p>
                <div class="add_bill">
                    <p class="costo_platillo">MX${{plato_fuerte.costo}}</p>
                    <a href="">+</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </section>
    <section class="bebidas">
        {% for bebida in bebidas%}
        <div class="card">
            <img src="{{bebida.imagen}}" alt="">
            <div class="info">
                <p class="nombre_platillo">{{bebida.nombre}}</p>
                <p class="descripcion_platillo">{{bebida.descripcion}} </p>
                <div class="add_bill">
                    <p class="costo_platillo">MX${{bebida.costo}}</p>
                    <a href="">+</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </section>
</body>
<script src="https://code.jquery.com/jquery-3.7.0.js"></script>
<script src="{% static 'js/panel.js'%}"></script>

</html>

App50Amigos/templates/panels/pedido.html
{%load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Carrito</title>
    <link href='https://fonts.googleapis.com/css?family=Nunito' rel='stylesheet'>
    <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico '%}" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'css/index.css'%}" rel="stylesheet" />
</head>

<body>
    <header>
        <div>
            <img src="{% static 'assets/Cinta/molletes.webp' %}" alt="">
            <img src="{% static 'assets/Cinta/Chilaquiles.webp' %}" alt="">
            <img src="{% static 'assets/Cinta/Pecado_Angelical.webp' %}" alt="">
            <img src="{% static 'assets/Cinta/pecado.webp' %}" alt="">
            <img src="{% static 'assets/Cinta/Platanos_Crema.webp' %}" alt="">
            <img src="{% static 'assets/Cinta/Pecado_Aquiles.webp' %}" alt="">
            <img src="{% static 'assets/Cinta/Pecado_Celestial.webp' %}" alt="">
            <img src="{% static 'assets/Cinta/fresas.webp' %}" alt="">
            <img src="{% static 'assets/Cinta/Mango_mamey.webp' %}" alt="">
        </div>
    </header>
    <section class="content">
        <div class="logo">
            <b class="bienvenido">Carrito</b>
            <div class="div_logo">
                <img src="{% static 'assets/logos/50amigos.png'%}" alt="">
            </div>
        </div>
        <div class="initial_form" id="initial_form">
            <p class="login">Iniciar sesión</p>
            <p class="ident">Soy:</p>
            <div class='links'>
                <button id="encargado">Responsable de Tabletas</button>
                <button id="admin">Administrador</button>
            </div>
        </div>
</body>
<script src="https://code.jquery.com/jquery-3.7.0.js"></script>
<script src="{% static 'js/index.js'%}"></script>
</html>

App50Amigos/templates/panels/votacion.html
{%load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Votación</title>
    <link href='https://fonts.googleapis.com/css?family=Nunito' rel='stylesheet'>
    <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico '%}" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'css/votacion.css'%}" rel="stylesheet" />
</head>

<body>
    <header>
        <div>
            <img src="{% static 'assets/Cinta/molletes.webp' %}" alt="">
            <img src="{% static 'assets/Cinta/Chilaquiles.webp' %}" alt="">
            <img src="{% static 'assets/Cinta/Pecado_Angelical.webp' %}" alt="">
            <img src="{% static 'assets/Cinta/pecado.webp' %}" alt="">
            <img src="{% static 'assets/Cinta/Platanos_Crema.webp' %}" alt="">
            <img src="{% static 'assets/Cinta/Pecado_Aquiles.webp' %}" alt="">
            <img src="{% static 'assets/Cinta/Pecado_Celestial.webp' %}" alt="">
            <img src="{% static 'assets/Cinta/fresas.webp' %}" alt="">
            <img src="{% static 'assets/Cinta/Mango_mamey.webp' %}" alt="">
        </div>
    </header>
    <section class="content">
        <div class="logo">
            <b class="bienvenido">Votación</b>
            <div class="div_logo">
                <img src="{% static 'assets/logos/50amigos.png'%}" alt="">
            </div>
        </div>
        <div class="initial_form" id="initial_form">
            <p class="login">Hola, indique cuántos comensales hay en la mesa</p>
            <p class="ident">Soy:</p>
            <div class='links'>
                <button id="encargado">Responsable de Tabletas</button>
                <button id="admin">Administrador</button>
            </div>
        </div>
</body>
<script src="https://code.jquery.com/jquery-3.7.0.js"></script>
<script src="{% static 'js/index.js'%}"></script>
</html>